#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III VI V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config normal_border_color "#484848"
# bspc config focused_border_color "#850d04"
# bspc config urgent_border_color "#B58900"
# bspc config presel_border_color "#26E2FF"

./.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/background.png &
picom --config /home/lira0003/.config/picom/picom.conf --experimental-backends -b &

