#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config gapless_monocle      true
bspc config borderless_monocle   true

bspc config focused_border_color     "#F0C674"
bspc config normal_border_color      "#6E6E6E"

./.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/Wallpaper-main/pexels-ragga-muffin-2468773.jpg &
vmware-user-suid-wrapper &
copypaste &
eng &
